version: "3.4"
services:
  mysql:
    image: mysql
    volumes:
      - ./mysqlData:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3307:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
      - UPLOAD_LIMIT=300M
    # restart: always
    ports:
      - 8083:80