version: '3.3'
services:
  db:
    image: mysql:5.7
    volumes:
      - ./mysqlData:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: utopiapp_db
      MYSQL_USER: david
      MYSQL_PASSWORD: root
    ports:
      - '3306:3306'
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
  web:
    depends_on:
      - db
    image: tomcat
    #volumes:
    #  - ./target/LoginWebApp-1.war:/usr/local/tomcat/webapps/LoginWebApp-1.war
    ports:
      - '8082:8080'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: utopiapp_db
      MYSQL_USER: david
      MYSQL_PASSWORD: root